### ISSUE TITLE
add support for ed25519 ssh keys

### ISSUE THREAD

**Issue by thayneq** [gogolith/GoCoEdit#65]
Please add support for ed25519 SSH keys. See 
https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54

**Comment by gogolith** [comment]
Added to the roadmap... but currently looks like libssh2 1.8.0 only supports openssl 1.1.0. ed25519 requires openssl 1.1.1.

**Comment by idnovic** [comment]
Please review this request. I need support for EdDSA keys too.
I am going to buy the app after you added it. Thank you!

**Comment by idnovic** [comment]
you need a version newer than the 2. august 2018
https://github.com/libssh2/libssh2/commit/03092292597ac601c3f9f0c267ecb145dda75e4e

maybe you could try a snapshot build, you can look at the github commits - not much changed since the last release so it should work fine
https://www.libssh2.org/snapshots/

**Comment by gogolith** [comment]
i'll check that for the next release, thanks...

**Comment by gogolith** [comment]
should work since GCE 15.2

**Comment by idnovic** [comment]
yes thank you! 

I bought GoCoEdit. Still need to try my key. Will let you know.
